/**
 * Share-to-X, for an opened setup and for a PnL card.
 *
 * This is what connecting X buys the user. Until it existed, "Share Setup" in
 * `TradeSuccessModal` closed the modal and did nothing, and step three of the
 * profile was an ask with no payoff behind it.
 *
 * Both composers go through `intentUrl`, so a post the user sends from the trade
 * modal and one they send from the profile's last step are the same mechanism —
 * which is what lets either of them credit that step.
 */

const APP_URL = "https://app.hyprearn.com";

/** @param {string} text */
function intentUrl(text) {
  const params = new URLSearchParams({ text, url: APP_URL });
  return `https://x.com/intent/post?${params}`;
}

/** @param {{ coin?: string }} [opts] */
export function setupShareText({ coin } = {}) {
  const market = coin ? `${coin} ` : "";
  return `Just opened a ${market}setup with the HyprEarn AI Copilot — entry, target and stop in one tap.`;
}

/** @param {{ coin?: string }} [opts] */
export function setupShareUrl(opts) {
  return intentUrl(setupShareText(opts));
}

/** @param {{ coin?: string }} [opts] */
export function openSetupShare(opts) {
  window.open(setupShareUrl(opts), "_blank", "noopener,noreferrer");
}

/**
 * The PnL card's caption. The numbers carry it, so the sentence stays out of
 * their way — everything that isn't a figure is there to say where the figures
 * came from.
 *
 * @param {{ coin?: string, side?: string, pnlPercent?: string }} [opts]
 */
export function pnlCardShareText({ coin, side, pnlPercent } = {}) {
  const position = [coin, side].filter(Boolean).join(" ");
  const move = pnlPercent ? ` ${pnlPercent}` : "";
  return position
    ? `${position}${move} — traded on HyprEarn with the AI Copilot.`
    : "My PnL card from HyprEarn, generated by the AI Copilot.";
}

/** @param {{ coin?: string, side?: string, pnlPercent?: string }} [opts] */
export function pnlCardShareUrl(opts) {
  return intentUrl(pnlCardShareText(opts));
}

/** @param {{ coin?: string, side?: string, pnlPercent?: string }} [opts] */
export function openPnlCardShare(opts) {
  window.open(pnlCardShareUrl(opts), "_blank", "noopener,noreferrer");
}
