/** Mock setups — Figma Terminal / AI Copilot (desktop 4039:11883, mobile feed 1017:24652). */
export const COPILOT_SETUPS = [
  {
    id: 'arb',
    tokenIcon: '/copilot-tokens/sui.png',
    symbol: 'ARB',
    price: 0.1131,
    balance: '6.93',
    title: 'ARB trend continuation short',
    direction: 'short',
    chips: [
      { kind: 'side', label: 'Short' },
      { kind: 'win', label: 'Winning %: 68%' },
      { kind: 'rr', label: 'R/R: 1:0' },
      { kind: 'range', label: 'Range: $0.1129 - $0.1134' },
      { kind: 'review', label: 'Review: 6h' },
    ],
    additional: {
      liquidation: '$0.1180',
      positionValue: '$800',
      marginReq: '$252',
      winning: '68%',
    },
  },
  {
    id: 'btc',
    tokenIcon: '/copilot-tokens/sol.png',
    symbol: 'BTC',
    price: 77453,
    balance: '12.40',
    title: 'BTC range-bound short near upper Bollinger',
    direction: 'short',
    chips: [
      { kind: 'side', label: 'Short' },
      { kind: 'win', label: 'Winning %: 65%' },
      { kind: 'rr', label: 'R/R: 1:0.06' },
      { kind: 'range', label: 'Range: $77259.37 - $77646.63' },
      { kind: 'review', label: 'Review: 4h' },
    ],
    additional: {
      liquidation: '$79200',
      positionValue: '$620',
      marginReq: '$198',
      winning: '65%',
    },
  },
  {
    id: 'wld',
    tokenIcon: '/copilot-tokens/eth.png',
    symbol: 'WLD',
    price: 0.2387,
    balance: '2.10',
    title: 'WLD trend continuation short',
    direction: 'short',
    chips: [
      { kind: 'side', label: 'Short' },
      { kind: 'win', label: 'Winning %: 64%' },
      { kind: 'rr', label: 'R/R: 1:0.25' },
      { kind: 'range', label: 'Range: $0.2372 - $0.2403' },
      { kind: 'review', label: 'Review: 12h' },
    ],
    additional: {
      liquidation: '$0.2450',
      positionValue: '$1,200',
      marginReq: '$310',
      winning: '64%',
    },
  },
]
