/** Mock setups — strategy × category matrix for AI Copilot prototype. */

export const COPILOT_CATEGORY_LABELS = {
  trending: "Trending",
  hip3: "HIP-3",
  bluechip: "Bluechip",
  spotlight: "Spotlight",
  tradexyz: "Trade[XYZ]",
  all: "All Setups",
};

/** @typedef {import('./copilotStrategies.js').DEFAULT_COPILOT_STRATEGY_ID} _ */

function setup({
  id,
  strategyId,
  category,
  tokenIcon,
  symbol,
  price,
  balance,
  title,
  direction,
  chips,
  additional,
}) {
  return {
    id,
    strategyId,
    category,
    tokenIcon,
    symbol,
    price,
    balance,
    title,
    direction,
    chips,
    additional,
  };
}

export const COPILOT_SETUPS = [
  // — Mean Reversion —
  setup({
    id: "arb-mr-trending",
    strategyId: "high-conviction",
    category: "trending",
    tokenIcon: "/copilot-tokens/sui.png",
    symbol: "ARB",
    price: 0.1131,
    balance: "6.93",
    title: "ARB fade short — stretched above VWAP",
    direction: "short",
    chips: [
      { kind: "side", label: "Short" },
      { kind: "win", label: "Winning %: 68%" },
      { kind: "rr", label: "R/R: 1:1.2" },
      { kind: "range", label: "Range: $0.1129 - $0.1134" },
      { kind: "review", label: "Review: 6h" },
    ],
    additional: {
      liquidation: "$0.1180",
      positionValue: "$800",
      marginReq: "$252",
      winning: "68%",
    },
  }),
  setup({
    id: "wld-mr-trending",
    strategyId: "high-conviction",
    category: "trending",
    tokenIcon: "/copilot-tokens/eth.png",
    symbol: "WLD",
    price: 0.2387,
    balance: "2.10",
    title: "WLD pullback short near upper band",
    direction: "short",
    chips: [
      { kind: "side", label: "Short" },
      { kind: "win", label: "Winning %: 64%" },
      { kind: "rr", label: "R/R: 1:0.25" },
      { kind: "range", label: "Range: $0.2372 - $0.2403" },
      { kind: "review", label: "Review: 12h" },
    ],
    additional: {
      liquidation: "$0.2450",
      positionValue: "$1,200",
      marginReq: "$310",
      winning: "64%",
    },
  }),
  setup({
    id: "purr-mr-hip3",
    strategyId: "high-conviction",
    category: "hip3",
    tokenIcon: "/copilot-tokens/sol.png",
    symbol: "PURR",
    price: 0.0842,
    balance: "4.20",
    title: "PURR range fade long at lower support",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 61%" },
      { kind: "rr", label: "R/R: 1:0.9" },
      { kind: "range", label: "Range: $0.0835 - $0.0851" },
      { kind: "review", label: "Review: 8h" },
    ],
    additional: {
      liquidation: "$0.0790",
      positionValue: "$540",
      marginReq: "$180",
      winning: "61%",
    },
  }),
  setup({
    id: "btc-mr-bluechip",
    strategyId: "high-conviction",
    category: "bluechip",
    tokenIcon: "/copilot-tokens/sol.png",
    symbol: "BTC",
    price: 77453,
    balance: "12.40",
    title: "BTC range-bound short near upper Bollinger",
    direction: "short",
    chips: [
      { kind: "side", label: "Short" },
      { kind: "win", label: "Winning %: 65%" },
      { kind: "rr", label: "R/R: 1:0.06" },
      { kind: "range", label: "Range: $77259 - $77646" },
      { kind: "review", label: "Review: 4h" },
    ],
    additional: {
      liquidation: "$79200",
      positionValue: "$620",
      marginReq: "$198",
      winning: "65%",
    },
  }),
  setup({
    id: "eth-mr-bluechip",
    strategyId: "high-conviction",
    category: "bluechip",
    tokenIcon: "/copilot-tokens/eth.png",
    symbol: "ETH",
    price: 2142.5,
    balance: "8.15",
    title: "ETH mean reversion long at daily support",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 62%" },
      { kind: "rr", label: "R/R: 1:0.8" },
      { kind: "range", label: "Range: $2135 - $2155" },
      { kind: "review", label: "Review: 6h" },
    ],
    additional: {
      liquidation: "$2080",
      positionValue: "$950",
      marginReq: "$285",
      winning: "62%",
    },
  }),
  setup({
    id: "sol-mr-spotlight",
    strategyId: "high-conviction",
    category: "spotlight",
    tokenIcon: "/copilot-tokens/sol.png",
    symbol: "SOL",
    price: 142.8,
    balance: "5.60",
    title: "SOL fade short at weekly resistance",
    direction: "short",
    chips: [
      { kind: "side", label: "Short" },
      { kind: "win", label: "Winning %: 59%" },
      { kind: "rr", label: "R/R: 1:1.1" },
      { kind: "range", label: "Range: $141.9 - $143.6" },
      { kind: "review", label: "Review: 5h" },
    ],
    additional: {
      liquidation: "$148.20",
      positionValue: "$710",
      marginReq: "$220",
      winning: "59%",
    },
  }),

  // — Momentum Breakout —
  setup({
    id: "sol-bo-trending",
    strategyId: "momentum-based",
    category: "trending",
    tokenIcon: "/copilot-tokens/sol.png",
    symbol: "SOL",
    price: 143.2,
    balance: "5.60",
    title: "SOL breakout long above $142 resistance",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 58%" },
      { kind: "rr", label: "R/R: 1:1.8" },
      { kind: "range", label: "Range: $142.0 - $145.5" },
      { kind: "review", label: "Review: 2h" },
    ],
    additional: {
      liquidation: "$138.50",
      positionValue: "$880",
      marginReq: "$275",
      winning: "58%",
    },
  }),
  setup({
    id: "arb-bo-trending",
    strategyId: "momentum-based",
    category: "trending",
    tokenIcon: "/copilot-tokens/sui.png",
    symbol: "ARB",
    price: 0.1148,
    balance: "6.93",
    title: "ARB continuation short below breakdown",
    direction: "short",
    chips: [
      { kind: "side", label: "Short" },
      { kind: "win", label: "Winning %: 57%" },
      { kind: "rr", label: "R/R: 1:1.5" },
      { kind: "range", label: "Range: $0.1140 - $0.1158" },
      { kind: "review", label: "Review: 1h" },
    ],
    additional: {
      liquidation: "$0.1195",
      positionValue: "$650",
      marginReq: "$210",
      winning: "57%",
    },
  }),
  setup({
    id: "hype-bo-hip3",
    strategyId: "momentum-based",
    category: "hip3",
    tokenIcon: "/copilot-tokens/eth.png",
    symbol: "HYPE",
    price: 18.42,
    balance: "3.10",
    title: "HYPE volume breakout long on HIP-3 listing",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 55%" },
      { kind: "rr", label: "R/R: 1:2.1" },
      { kind: "range", label: "Range: $18.1 - $19.2" },
      { kind: "review", label: "Review: 1h" },
    ],
    additional: {
      liquidation: "$17.20",
      positionValue: "$1,100",
      marginReq: "$340",
      winning: "55%",
    },
  }),
  setup({
    id: "avax-bo-spotlight",
    strategyId: "momentum-based",
    category: "spotlight",
    tokenIcon: "/copilot-tokens/sui.png",
    symbol: "AVAX",
    price: 28.65,
    balance: "7.20",
    title: "AVAX expansion breakout long",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 56%" },
      { kind: "rr", label: "R/R: 1:1.6" },
      { kind: "range", label: "Range: $28.2 - $29.4" },
      { kind: "review", label: "Review: 3h" },
    ],
    additional: {
      liquidation: "$27.40",
      positionValue: "$720",
      marginReq: "$230",
      winning: "56%",
    },
  }),

  // — Trend Following —
  setup({
    id: "wld-tf-trending",
    strategyId: "v3-risk-engine",
    category: "trending",
    tokenIcon: "/copilot-tokens/eth.png",
    symbol: "WLD",
    price: 0.241,
    balance: "2.10",
    title: "WLD downtrend continuation short",
    direction: "short",
    chips: [
      { kind: "side", label: "Short" },
      { kind: "win", label: "Winning %: 63%" },
      { kind: "rr", label: "R/R: 1:1.3" },
      { kind: "range", label: "Range: $0.239 - $0.243" },
      { kind: "review", label: "Review: 8h" },
    ],
    additional: {
      liquidation: "$0.2480",
      positionValue: "$900",
      marginReq: "$280",
      winning: "63%",
    },
  }),
  setup({
    id: "doge-tf-trending",
    strategyId: "v3-risk-engine",
    category: "trending",
    tokenIcon: "/copilot-tokens/sol.png",
    symbol: "DOGE",
    price: 0.162,
    balance: "11.5",
    title: "DOGE uptrend pullback long",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 60%" },
      { kind: "rr", label: "R/R: 1:1.0" },
      { kind: "range", label: "Range: $0.160 - $0.165" },
      { kind: "review", label: "Review: 6h" },
    ],
    additional: {
      liquidation: "$0.155",
      positionValue: "$480",
      marginReq: "$150",
      winning: "60%",
    },
  }),
  setup({
    id: "kbonk-tf-hip3",
    strategyId: "v3-risk-engine",
    category: "hip3",
    tokenIcon: "/copilot-tokens/sui.png",
    symbol: "KBONK",
    price: 0.0000284,
    balance: "9.80",
    title: "KBONK trend long with higher lows intact",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 54%" },
      { kind: "rr", label: "R/R: 1:1.4" },
      { kind: "range", label: "Range: $0.000027 - $0.000029" },
      { kind: "review", label: "Review: 4h" },
    ],
    additional: {
      liquidation: "$0.000026",
      positionValue: "$420",
      marginReq: "$130",
      winning: "54%",
    },
  }),
  setup({
    id: "btc-tf-bluechip",
    strategyId: "v3-risk-engine",
    category: "bluechip",
    tokenIcon: "/copilot-tokens/sol.png",
    symbol: "BTC",
    price: 77820,
    balance: "12.40",
    title: "BTC higher-high trend long on 4h structure",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 66%" },
      { kind: "rr", label: "R/R: 1:0.9" },
      { kind: "range", label: "Range: $77500 - $78200" },
      { kind: "review", label: "Review: 12h" },
    ],
    additional: {
      liquidation: "$76200",
      positionValue: "$1,050",
      marginReq: "$320",
      winning: "66%",
    },
  }),
  setup({
    id: "eth-tf-bluechip",
    strategyId: "v3-risk-engine",
    category: "bluechip",
    tokenIcon: "/copilot-tokens/eth.png",
    symbol: "ETH",
    price: 2168,
    balance: "8.15",
    title: "ETH trend long — EMA stack aligned",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 64%" },
      { kind: "rr", label: "R/R: 1:0.7" },
      { kind: "range", label: "Range: $2155 - $2185" },
      { kind: "review", label: "Review: 8h" },
    ],
    additional: {
      liquidation: "$2100",
      positionValue: "$890",
      marginReq: "$270",
      winning: "64%",
    },
  }),

  // — Funding Capture —
  setup({
    id: "hype-fc-hip3",
    strategyId: "v3-risk-engine",
    category: "hip3",
    tokenIcon: "/copilot-tokens/eth.png",
    symbol: "HYPE",
    price: 18.35,
    balance: "3.10",
    title: "HYPE positive funding carry long",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 71%" },
      { kind: "rr", label: "R/R: 1:0.4" },
      { kind: "range", label: "Range: $18.1 - $18.6" },
      { kind: "review", label: "Review: 24h" },
    ],
    additional: {
      liquidation: "$16.80",
      positionValue: "$2,400",
      marginReq: "$600",
      winning: "71%",
    },
  }),
  setup({
    id: "purr-fc-hip3",
    strategyId: "v3-risk-engine",
    category: "hip3",
    tokenIcon: "/copilot-tokens/sol.png",
    symbol: "PURR",
    price: 0.0851,
    balance: "4.20",
    title: "PURR funding arb — short perp / long spot",
    direction: "short",
    chips: [
      { kind: "side", label: "Short" },
      { kind: "win", label: "Winning %: 69%" },
      { kind: "rr", label: "R/R: 1:0.3" },
      { kind: "range", label: "Range: $0.0845 - $0.0858" },
      { kind: "review", label: "Review: 24h" },
    ],
    additional: {
      liquidation: "$0.0895",
      positionValue: "$1,800",
      marginReq: "$450",
      winning: "69%",
    },
  }),
  setup({
    id: "btc-fc-bluechip",
    strategyId: "v3-risk-engine",
    category: "bluechip",
    tokenIcon: "/copilot-tokens/sol.png",
    symbol: "BTC",
    price: 77380,
    balance: "12.40",
    title: "BTC funding capture — delta-neutral carry",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 74%" },
      { kind: "rr", label: "R/R: 1:0.2" },
      { kind: "range", label: "Range: $77100 - $77650" },
      { kind: "review", label: "Review: 48h" },
    ],
    additional: {
      liquidation: "$75500",
      positionValue: "$5,200",
      marginReq: "$1,100",
      winning: "74%",
    },
  }),
  setup({
    id: "eth-fc-bluechip",
    strategyId: "v3-risk-engine",
    category: "bluechip",
    tokenIcon: "/copilot-tokens/eth.png",
    symbol: "ETH",
    price: 2138,
    balance: "8.15",
    title: "ETH perp funding harvest long",
    direction: "long",
    chips: [
      { kind: "side", label: "Long" },
      { kind: "win", label: "Winning %: 72%" },
      { kind: "rr", label: "R/R: 1:0.25" },
      { kind: "range", label: "Range: $2125 - $2155" },
      { kind: "review", label: "Review: 48h" },
    ],
    additional: {
      liquidation: "$2060",
      positionValue: "$3,600",
      marginReq: "$820",
      winning: "72%",
    },
  }),
  setup({
    id: "arb-fc-trending",
    strategyId: "v3-risk-engine",
    category: "trending",
    tokenIcon: "/copilot-tokens/sui.png",
    symbol: "ARB",
    price: 0.1128,
    balance: "6.93",
    title: "ARB elevated funding short bias",
    direction: "short",
    chips: [
      { kind: "side", label: "Short" },
      { kind: "win", label: "Winning %: 67%" },
      { kind: "rr", label: "R/R: 1:0.35" },
      { kind: "range", label: "Range: $0.1120 - $0.1138" },
      { kind: "review", label: "Review: 12h" },
    ],
    additional: {
      liquidation: "$0.1175",
      positionValue: "$1,100",
      marginReq: "$290",
      winning: "67%",
    },
  }),
];

/**
 * @param {{ strategyId: string, categoryId: string }} params
 */
export function getCopilotSetups({ strategyId, categoryId }) {
  return COPILOT_SETUPS.filter((s) => {
    if (s.strategyId !== strategyId) return false;
    if (categoryId === "all") return true;
    return s.category === categoryId;
  });
}
