import BottomSheet from "../BottomSheet.jsx";
import AppButton from "../AppButton.jsx";
import AppIcon from "../AppIcon.jsx";
import { appIcons } from "../mobileAssets.js";

const POINTS = [
  {
    icon: appIcons.navCopilot,
    title: "Generated by AI",
    body: "Each setup is produced by the strategy you pick at the top. Change the strategy to change how strict the filter is.",
  },
  {
    icon: appIcons.timer20,
    title: "They expire",
    body: "Setups are built from a market snapshot and go stale. The ring on the refresh button shows how long the current batch stays valid.",
  },
  {
    icon: appIcons.shieldCheck16,
    title: "You stay in control",
    body: "Nothing is placed for you. Backtest a setup, then review size, leverage and TP/SL in the ticket before opening a position.",
  },
];

/**
 * "About these setups" — the AI disclosure the feed links to.
 *
 * Apple HIG › Generative AI: tell people where AI is used, set expectations
 * about its limits, and keep them in charge. Kept to three facts so it reads
 * as orientation, not a terms page.
 */
export default function CopilotAboutSheet({ open, onClose, onRunTutorial }) {
  return (
    <BottomSheet open={open} onClose={onClose} title="About AI setups">
      <div className="flex flex-col gap-5 px-4 pt-4">
        <ul className="flex flex-col gap-4">
          {POINTS.map((p) => (
            <li key={p.title} className="flex gap-3">
              <span className="flex size-9 shrink-0 items-center justify-center rounded-full bg-app-subtle text-app-accent">
                <AppIcon src={p.icon} size={18} />
              </span>
              <div className="flex min-w-0 flex-col gap-0.5">
                <p className="text-app-body font-medium text-ink">{p.title}</p>
                <p className="text-app-callout text-ink-muted">{p.body}</p>
              </div>
            </li>
          ))}
        </ul>
        <p className="rounded-lg bg-app-subtle px-3 py-2.5 text-app-caption text-ink-subtle">
          AI setups can be wrong and are not financial advice. Past win rates don't guarantee
          future results.
        </p>
        {onRunTutorial ? (
          <AppButton
            variant="secondary"
            onClick={() => {
              onClose?.();
              onRunTutorial();
            }}
          >
            Walk me through it
          </AppButton>
        ) : null}
      </div>
    </BottomSheet>
  );
}
