/** Agent Logs proto — mock feed (mirrors future API shape). */

export const AGENT_LOG_CATEGORIES = [
  { id: "AGENT_SETUP", label: "Agent & exchange setup", defaultEnabled: true },
  { id: "VAULT_TRADE", label: "Vault trades", defaultEnabled: true },
  { id: "VAULT_OPS", label: "Vault operations", defaultEnabled: true },
  { id: "PERP_AGENT", label: "Perp AI agent", defaultEnabled: true },
  { id: "ACCOUNT", label: "Account & vault config", defaultEnabled: true },
  { id: "SYSTEM", label: "System & connectivity", defaultEnabled: false },
];

/** vaultId keys align with `vaultsMockData.js` row ids. */
export const VAULT_AGENT_LOG_NAMES = {
  bluechip: "BlueChip Vault",
  "hip3-featured": "HIP-3 Vault",
  trending: "Trending Vault",
};

const now = Date.now();
const mins = (m) => new Date(now - m * 60 * 1000).toISOString();
const hours = (h) => new Date(now - h * 60 * 60 * 1000).toISOString();
const days = (d) => new Date(now - d * 24 * 60 * 60 * 1000).toISOString();

export const INITIAL_AGENT_LOGS = [
  {
    id: "log-1",
    vaultId: "bluechip",
    category: "VAULT_TRADE",
    severity: "critical",
    eventCode: "VAULT_PLACE_TRADE_FAILED",
    title: "Vault trade failed",
    body: "Agent wallet expired. Trade execution failed due to authentication error.",
    exchange: "hyperliquid",
    symbol: "BTC/USDC:USDC",
    occurrenceCount: 3,
    firstOccurredAt: hours(6),
    lastOccurredAt: mins(2),
    readAt: null,
    cta: { type: "renew_hl_agent", label: "Renew API Wallet" },
    tags: ["HYPERLIQUID", "TRADE EXECUTION"],
  },
  {
    id: "log-2",
    vaultId: null,
    category: "AGENT_SETUP",
    severity: "critical",
    eventCode: "API_WALLET_EXPIRED",
    title: "Hyperliquid agent wallet expired",
    body: "Your API wallet authorization has expired. Renew to avoid automated strategy interruptions.",
    exchange: "hyperliquid",
    symbol: null,
    occurrenceCount: 1,
    firstOccurredAt: hours(1),
    lastOccurredAt: mins(15),
    readAt: null,
    cta: { type: "renew_hl_agent", label: "Renew API Wallet" },
    tags: ["HYPERLIQUID", "AGENT SETUP"],
  },
  {
    id: "log-3",
    vaultId: "trending",
    category: "VAULT_OPS",
    severity: "action_required",
    eventCode: "LOW_EXCHANGE_BALANCE",
    title: "Low balance — Pacifica",
    body: "Agent wallet balance is below the minimum threshold required ($32.10). Top up to keep vault trades running.",
    exchange: "pacifica",
    symbol: null,
    occurrenceCount: 1,
    firstOccurredAt: hours(2),
    lastOccurredAt: mins(62),
    readAt: null,
    cta: { type: "deposit", label: "Deposit" },
    tags: ["PACIFICA", "WALLET BALANCE"],
  },
  {
    id: "log-4",
    vaultId: "bluechip",
    category: "ACCOUNT",
    severity: "success",
    eventCode: "VAULT_ACTIVATED",
    title: "Vault activated",
    body: "Agent is now active and executing strategy as expected.",
    exchange: "hyperliquid",
    symbol: null,
    occurrenceCount: 1,
    firstOccurredAt: hours(3),
    lastOccurredAt: hours(3),
    readAt: new Date().toISOString(),
    cta: { type: "view_vault", label: "View vault" },
    tags: ["HYPERLIQUID", "VAULT ACTIVATION"],
  },
  {
    id: "log-5",
    vaultId: null,
    category: "PERP_AGENT",
    severity: "info",
    eventCode: "AUTO_REVIEW_ACTION",
    title: "Auto-review: HOLD — ETH position",
    body: "Thesis intact; next review in 2h.",
    exchange: "hyperliquid",
    symbol: "ETH/USDC:USDC",
    occurrenceCount: 1,
    firstOccurredAt: hours(4),
    lastOccurredAt: hours(4),
    readAt: new Date().toISOString(),
    cta: { type: "view_position", label: "View review" },
    tags: ["HYPERLIQUID", "PERP AGENT"],
  },
  {
    id: "log-6",
    vaultId: "bluechip",
    category: "VAULT_OPS",
    severity: "warning",
    eventCode: "VAULT_VALIDATION_SKIPPED",
    title: "Trade skipped — validation failed",
    body: "DEX profile validation did not pass for this cycle. Trade was skipped; will retry next cron.",
    exchange: "paradex",
    symbol: "SOL/USDC:USDC",
    occurrenceCount: 2,
    firstOccurredAt: hours(5),
    lastOccurredAt: hours(5),
    readAt: null,
    cta: null,
    tags: ["PARADEX", "VAULT OPS"],
  },
  {
    id: "log-7",
    vaultId: null,
    category: "SYSTEM",
    severity: "warning",
    eventCode: "VAULT_DEX_API_FAILURE",
    title: "DEX API transient error",
    body: "Hyperliquid API returned a rate-limit response. Retrying automatically.",
    exchange: "hyperliquid",
    symbol: null,
    occurrenceCount: 4,
    firstOccurredAt: days(1),
    lastOccurredAt: days(1),
    readAt: new Date().toISOString(),
    cta: null,
    tags: ["HYPERLIQUID", "SYSTEM"],
  },
  {
    id: "log-8",
    vaultId: null,
    category: "AGENT_SETUP",
    severity: "action_required",
    eventCode: "AGENT_NOT_APPROVED",
    title: "Pacifica agent not approved",
    body: "Approve the agent wallet to enable automated trading on Pacifica.",
    exchange: "pacifica",
    symbol: null,
    occurrenceCount: 1,
    firstOccurredAt: days(1),
    lastOccurredAt: days(1),
    readAt: null,
    cta: { type: "approve_pacifica_agent", label: "Approve agent" },
    tags: ["PACIFICA", "AGENT SETUP"],
  },
  {
    id: "log-9",
    vaultId: "bluechip",
    category: "VAULT_TRADE",
    severity: "critical",
    eventCode: "VAULT_CLOSE_TRADE_FAILED",
    title: "Close trade failed — BTC long",
    body: "Could not close position. Authorization may have expired.",
    exchange: "hyperliquid",
    symbol: "BTC/USDC:USDC",
    occurrenceCount: 1,
    firstOccurredAt: days(1),
    lastOccurredAt: days(1),
    readAt: null,
    cta: { type: "renew_hl_agent", label: "Renew API Wallet" },
    tags: ["HYPERLIQUID", "TRADE EXECUTION"],
  },
  {
    id: "log-10",
    vaultId: "trending",
    category: "ACCOUNT",
    severity: "info",
    eventCode: "VAULT_MARGIN_UPDATED",
    title: "Margin updated",
    body: "Allocation margin changed from 5% to 10%.",
    exchange: "hyperliquid",
    symbol: null,
    occurrenceCount: 1,
    firstOccurredAt: days(2),
    lastOccurredAt: days(2),
    readAt: new Date().toISOString(),
    cta: { type: "view_vault", label: "View vault" },
    tags: ["HYPERLIQUID", "ACCOUNT"],
  },
];

export const MORE_AGENT_LOGS = [
  {
    id: "log-11",
    vaultId: null,
    category: "PERP_AGENT",
    severity: "warning",
    eventCode: "AUTO_REVIEW_FAILED",
    title: "Auto-review failed — SOL position",
    body: "Review service timed out. Will retry on next cycle.",
    exchange: "hyperliquid",
    symbol: "SOL/USDC:USDC",
    occurrenceCount: 1,
    firstOccurredAt: days(2),
    lastOccurredAt: days(2),
    readAt: null,
    cta: { type: "view_position", label: "View review" },
    tags: ["HYPERLIQUID", "PERP AGENT"],
  },
  {
    id: "log-12",
    vaultId: "hip3-featured",
    category: "VAULT_OPS",
    severity: "critical",
    eventCode: "DELTA_NEUTRAL_LEG_MISMATCH",
    title: "Delta-neutral leg mismatch",
    body: "Long and short legs are out of balance. Manual review recommended.",
    exchange: "hyperliquid",
    symbol: null,
    occurrenceCount: 1,
    firstOccurredAt: days(3),
    lastOccurredAt: days(3),
    readAt: null,
    cta: { type: "view_vault", label: "View vault" },
    tags: ["HYPERLIQUID", "VAULT OPS"],
  },
  {
    id: "log-13",
    vaultId: "hip3-featured",
    category: "ACCOUNT",
    severity: "info",
    eventCode: "VAULT_DEACTIVATED",
    title: "Vault deactivated",
    body: "Automated strategy stopped. Positions remain open until manually closed.",
    exchange: "hyperliquid",
    symbol: null,
    occurrenceCount: 1,
    firstOccurredAt: days(3),
    lastOccurredAt: days(3),
    readAt: null,
    cta: { type: "view_vault", label: "View vault" },
    tags: ["HYPERLIQUID", "ACCOUNT"],
  },
];
